// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	outputport "adg/internal/application/outputport"

	mock "github.com/stretchr/testify/mock"
)

// DecisionPrint is an autogenerated mock type for the DecisionPrint type
type DecisionPrint struct {
	mock.Mock
}

// Printed provides a mock function with given fields: bodies, sections
func (_m *DecisionPrint) Printed(bodies []outputport.DecisionBody, sections map[string]bool) {
	_m.Called(bodies, sections)
}

// NewDecisionPrint creates a new instance of DecisionPrint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionPrint(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionPrint {
	mock := &DecisionPrint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
