// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionSupersede is an autogenerated mock type for the DecisionSupersede type
type DecisionSupersede struct {
	mock.Mock
}

// Superseded provides a mock function with given fields: newID, oldID
func (_m *DecisionSupersede) Superseded(newID string, oldID string) {
	_m.Called(newID, oldID)
}

// NewDecisionSupersede creates a new instance of DecisionSupersede. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionSupersede(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionSupersede {
	mock := &DecisionSupersede{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
