// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	outputport "adg/internal/application/outputport"

	mock "github.com/stretchr/testify/mock"
)

// ModelMigrate is an autogenerated mock type for the ModelMigrate type
type ModelMigrate struct {
	mock.Mock
}

// Migrated provides a mock function with given fields: steps, dryRun
func (_m *ModelMigrate) Migrated(steps []outputport.MigrationStep, dryRun bool) {
	_m.Called(steps, dryRun)
}

// NewModelMigrate creates a new instance of ModelMigrate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelMigrate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelMigrate {
	mock := &ModelMigrate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
