// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DecisionSupersede is an autogenerated mock type for the DecisionSupersede type
type DecisionSupersede struct {
	mock.Mock
}

// Supersede provides a mock function with given fields: modelPath, newID, newTitle, oldID, oldTitle, rationale
func (_m *DecisionSupersede) Supersede(modelPath string, newID string, newTitle string, oldID string, oldTitle string, rationale string) error {
	ret := _m.Called(modelPath, newID, newTitle, oldID, oldTitle, rationale)

	if len(ret) == 0 {
		panic("no return value specified for Supersede")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string) error); ok {
		r0 = rf(modelPath, newID, newTitle, oldID, oldTitle, rationale)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDecisionSupersede creates a new instance of DecisionSupersede. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDecisionSupersede(t interface {
	mock.TestingT
	Cleanup(func())
}) *DecisionSupersede {
	mock := &DecisionSupersede{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
