// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ModelMigrate is an autogenerated mock type for the ModelMigrate type
type ModelMigrate struct {
	mock.Mock
}

// Migrate provides a mock function with given fields: modelPath, dryRun
func (_m *ModelMigrate) Migrate(modelPath string, dryRun bool) error {
	ret := _m.Called(modelPath, dryRun)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(modelPath, dryRun)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewModelMigrate creates a new instance of ModelMigrate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelMigrate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelMigrate {
	mock := &ModelMigrate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
