// Code generated by mockery v2.53.6. DO NOT EDIT.

package model

import mock "github.com/stretchr/testify/mock"

// MockModelRepository is an autogenerated mock type for the ModelRepository type
type MockModelRepository struct {
	mock.Mock
}

// CreateModel provides a mock function with given fields: modelPath
func (_m *MockModelRepository) CreateModel(modelPath string) error {
	ret := _m.Called(modelPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateModel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(modelPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: modelPath
func (_m *MockModelRepository) Exists(modelPath string) bool {
	ret := _m.Called(modelPath)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(modelPath)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockModelRepository creates a new instance of MockModelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelRepository {
	mock := &MockModelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
