// Code generated by mockery v2.53.6. DO NOT EDIT.

package decision

import (
	madr "adg/internal/domain/decision/madr"

	mock "github.com/stretchr/testify/mock"
)

// MockDecisionRepository is an autogenerated mock type for the DecisionRepository type
type MockDecisionRepository struct {
	mock.Mock
}

// Copy provides a mock function with given fields: srcPath, dstPath, decisionID
func (_m *MockDecisionRepository) Copy(srcPath string, dstPath string, decisionID string) error {
	ret := _m.Called(srcPath, dstPath, decisionID)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(srcPath, dstPath, decisionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: modelPath, subFolderPath, decision
func (_m *MockDecisionRepository) Create(modelPath string, subFolderPath string, decision *madr.Decision) (*madr.Decision, error) {
	ret := _m.Called(modelPath, subFolderPath, decision)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *madr.Decision
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *madr.Decision) (*madr.Decision, error)); ok {
		return rf(modelPath, subFolderPath, decision)
	}
	if rf, ok := ret.Get(0).(func(string, string, *madr.Decision) *madr.Decision); ok {
		r0 = rf(modelPath, subFolderPath, decision)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*madr.Decision)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *madr.Decision) error); ok {
		r1 = rf(modelPath, subFolderPath, decision)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDecisionFile provides a mock function with given fields: modelPath, id
func (_m *MockDecisionRepository) FindDecisionFile(modelPath string, id string) (string, error) {
	ret := _m.Called(modelPath, id)

	if len(ret) == 0 {
		panic("no return value specified for FindDecisionFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(modelPath, id)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(modelPath, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(modelPath, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAll provides a mock function with given fields: modelPath
func (_m *MockDecisionRepository) LoadAll(modelPath string) ([]madr.Decision, error) {
	ret := _m.Called(modelPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []madr.Decision
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]madr.Decision, error)); ok {
		return rf(modelPath)
	}
	if rf, ok := ret.Get(0).(func(string) []madr.Decision); ok {
		r0 = rf(modelPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]madr.Decision)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(modelPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadBody provides a mock function with given fields: modelPath, id
func (_m *MockDecisionRepository) LoadBody(modelPath string, id string) (string, error) {
	ret := _m.Called(modelPath, id)

	if len(ret) == 0 {
		panic("no return value specified for LoadBody")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(modelPath, id)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(modelPath, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(modelPath, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadById provides a mock function with given fields: modelPath, id
func (_m *MockDecisionRepository) LoadById(modelPath string, id string) (*madr.Decision, error) {
	ret := _m.Called(modelPath, id)

	if len(ret) == 0 {
		panic("no return value specified for LoadById")
	}

	var r0 *madr.Decision
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*madr.Decision, error)); ok {
		return rf(modelPath, id)
	}
	if rf, ok := ret.Get(0).(func(string, string) *madr.Decision); ok {
		r0 = rf(modelPath, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*madr.Decision)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(modelPath, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadByTitle provides a mock function with given fields: modelPath, title
func (_m *MockDecisionRepository) LoadByTitle(modelPath string, title string) (*madr.Decision, error) {
	ret := _m.Called(modelPath, title)

	if len(ret) == 0 {
		panic("no return value specified for LoadByTitle")
	}

	var r0 *madr.Decision
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*madr.Decision, error)); ok {
		return rf(modelPath, title)
	}
	if rf, ok := ret.Get(0).(func(string, string) *madr.Decision); ok {
		r0 = rf(modelPath, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*madr.Decision)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(modelPath, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: modelPath, decision, body
func (_m *MockDecisionRepository) Save(modelPath string, decision *madr.Decision, body string) error {
	ret := _m.Called(modelPath, decision, body)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *madr.Decision, string) error); ok {
		r0 = rf(modelPath, decision, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDecisionRepository creates a new instance of MockDecisionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecisionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecisionRepository {
	mock := &MockDecisionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
